language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - travis/before_install.sh

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - travis/script.sh

after_script:
  - travis/after_script.sh
